### ISSUE TITLE
Does it work with Mi band 7?

### ISSUE THREAD

**Issue by jeanp117** [gzalo/miband-6-heart-rate-monitor#4]
Sorry, this is not an issue but I need to ask 

I just tried it with a mi band 6 but I want to know if it works on 7 too 

@gzalo

**Comment by gzalo** [comment]
Hi! I don't think so, and I don't have a Mi band 7 to try.

But there's this fork which should work: https://github.com/patyork/miband-7-monitor

Let me know if that solves the issue!

**Comment by jeanp117** [comment]
Thank you very much, Trust me, I searched before asking 🥺 . I'm glad that there is a version and that it is also based on your code.
